---
stages:
  - linkchecker
  - build

linkchecker:
  stage: linkchecker
  image: python:3.7-alpine
  only:
    - schedules
  script:
    - apk add --no-cache git bash curl
    - bash .ci/linkchecker.sh

build:
  stage: build
  image: python:3.7-alpine
  script:
    - pip install -r requirements.txt
    - sphinx-build -W -b linkcheck . _build
