---
stages:
  - linkchecker
  - spellchecker
  - build

linkchecker:
  stage: linkchecker
  image: python:3.7-alpine
  only:
    - schedules
  script:
    - apk add --no-cache git bash curl
    - bash .ci/linkchecker.sh

spellchecker: # Name of job
  stage: spellchecker # Name of the stage the job is part of
  image: python:3.7-alpine # Which container to run
  script:
    - apk add --no-cache bash curl # Install curl etc.
    - curl -L -o ./install-misspell.sh https://git.io/misspell # Download
    - bash ./install-misspell.sh # Install
    - ./bin/misspell -error . # Run misspell on all files

build:
  stage: build
  when: on_success
  image: python:3.7-alpine
  script:
    - pip install -r requirements.txt
    # '-W': Turn warnings into errors
    # '--keep-going': When encountering a warning continue to process (this
    # allows us to capture multiple warnings at the same time, avoiding the
    # 'build->warning->fix->build->warning' loop where both fixes could be
    # solved at the same time)
    # '-n': Warn about internal missing references
    - sphinx-build -W --keep-going -n . _build
