---
stages:
  - linkchecker
  - spellchecker
  - build

linkchecker:
  stage: linkchecker
  image: python:3.7-alpine
  only:
    - schedules
  script:
    - apk add --no-cache git bash curl
    - bash .ci/linkchecker.sh

spellchecker: # Name of job
  stage: spellchecker # Name of the stage the job is part of
  image: python:3.7-alpine # Which container to run
  script:
    - apk add --no-cache bash curl # Install curl etc.
    - curl -L -o ./install-misspell.sh https://git.io/misspell # Download
    - bash ./install-misspell.sh # Install
    - ./bin/misspell -error . # Run misspell on all files

build:
  stage: build
  when: on_success
  image: python:3.7-alpine
  script:
    - pip install -r requirements.txt
    - sphinx-build -W -b linkcheck . _build
